---
#ServiceAccount Create
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
---
#Cluster-admin permission
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: jenkins-sa
    namespace: default
